version: "3.7"
services:
  portal-db:
    container_name: portal-database
    restart: unless-stopped
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - portal-database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    expose:
      - "5432"
    networks:
      - root_proxy-nety
  portal-frontend:
    container_name: portal-frontend
    restart: "no"
    image: "node:14"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: >
      sh -c "cd server && npm install && npm run build:frontend"
    networks:
      - root_proxy-nety
  portal-backend:
    container_name: portal-backend
    restart: unless-stopped
    image: "node:14"
    depends_on:
      - portal-db
    expose:
      - "80"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: >
      sh -c "cd server && npm install && npm run db:migrate && npm run db:seed && npm start"
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      #NODE_ENV: production
      DATABASE_URL: "portal-db"
      DATABASE_PASSWORD: $POSTGRES_PASSWORD
      DATABASE_USER: $POSTGRES_USER
      DATABASE_NAME: $POSTGRES_DB
      LOGGING: "true"
      PORT: 80
    networks:
      - root_proxy-nety
volumes:
  portal-database-data: # named volumes can be managed easier using docker-compose
  
networks:
  root_proxy-nety:
    external: true
