import {RouterModule} from '@angular/router';
import {OverviewComponent} from './overview/overview.component';
import {UsersComponent} from './users/users.component';
import {EventsComponent} from "./events/events.component";
import {RolesComponent} from "./roles/roles.component";
import {TeamsComponent} from "./teams/teams.component";
import {PollsComponent} from "./polls/polls.component";
import {StatsComponent} from "./stats/stats.component";
import {NewsComponent} from './news/news.component';
import {PollAnswerDetailComponent} from './polls/poll-answer-detail/poll-answer-detail.component';
import {DirectDebitMandatesComponent} from './direct-debit-mandates/direct-debit-mandates.component';
import {DocumentsComponent} from './documents/documents.component';
import {Oauth2Component} from './oauth2/oauth2.component';
import {PrivacyComponent} from './privacy/privacy.component';
import {EventLogComponent} from './event-log/event-log.component';
import {FormsComponent} from './forms/forms.component';
import {ThemeComponent} from './theme/theme.component';
import {ShopComponent} from './shop/shop.component';
import {InventoryComponent} from './inventory/inventory.component';
import {EventRegistrationsComponent} from './events/event-registrations/event-registrations.component';

export const adminRoutes = RouterModule.forChild([
  {path: '', pathMatch: 'full', component: OverviewComponent},
  {path: 'theme', component: ThemeComponent},
  {path: 'stats', component: StatsComponent},
  {path: 'users', component: UsersComponent},
  {path: 'users/:id', component: UsersComponent},
  {path: 'events', component: EventsComponent},
  {path: 'events/:id', component: EventsComponent},
  {path: 'events/:id/registrations', component: EventRegistrationsComponent},
  {path: 'teams', component: TeamsComponent},
  {path: 'teams/:id', component: TeamsComponent},
  {path: 'news', component: NewsComponent},
  {path: 'news/:id', component: NewsComponent},
  {path: 'forms', component: FormsComponent},
  {path: 'forms/:id', component: FormsComponent},
  {path: 'shop', component: ShopComponent},
  {path: 'shop/:id', component: ShopComponent},
  {path: 'inventory', component: InventoryComponent},
  {path: 'inventory/:id', component: InventoryComponent},
  {path: 'training', component: InventoryComponent},
  {path: 'training/:id', component: InventoryComponent},
  {path: 'polls', component: PollsComponent},
  {path: 'polls/:id', component: PollAnswerDetailComponent},
  {path: 'roles', component: RolesComponent},
  {path: 'direct-debit-mandates', component: DirectDebitMandatesComponent},
  {path: 'documents', component: DocumentsComponent},
  {path: 'oauth2', component: Oauth2Component},
  {path: 'privacy', component: PrivacyComponent},
  {path: 'event-log', component: EventLogComponent},
]);
